name: HeroesAndWars
version: ${project.version}
main: opkarol.heroeswars.Heroeswars
api-version: 1.17
authors: [ OpKarol ]
description: Fun minigame

commands:
  class:
    description: Opens gui with classes
  entity:
